[package]
name = "cctalk"
version = "0.1.2"
edition = "2024"

[dependencies]
crc16 = "0.4.0" #unsure about no_std
embedded-hal = "1.0.0" #no_std compat
embedded-hal-mock = { version = "0.11.1", features = [ "eh1" ] } #no_std compat
embedded-hal-nb = "1.0" #no_std compat
embedded-io = "0.6" #no_std compat
heapless = "0.9.3" #no_std compat
# mock-embedded-io = "0.1.0"
nb = "1.1.0" #no_std compat
spin = "0.12.3" #no_std_compat
thiserror = { version = "2.0.20", default-features = false } #no_std compat
