[package]
name = "cctalk"
version = "0.1.0"
edition = "2024"

[dependencies]
crc16 = "0.4.0"
embedded-hal = "1.0.0"
embedded-hal-mock = { version = "0.11.1", features = [ "eh1" ] }
embedded-hal-nb = "1.0"
embedded-io = "0.6"
heapless = "0.9.3"
# mock-embedded-io = "0.1.0"
nb = "1.1.0"
thiserror = "2.0.20"
