use std::convert::TryFrom;

#[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Eq, Hash)]
#[repr(u8)]
pub enum CcTalkHeader {
    // --- 0 to 9: Response & Broadcast Codes ---
    Ack = 0,
    ResetDevice = 1,
    Broadcast = 2,
    Nak = 5,
    Busy = 6,

    UknownHeader = 99,
    // --- 100 to 109: Escrow & Expansion ---
    RequestEscrowStatus = 106,
    OperateEscrow = 107,
    SwitchEncryptionKey = 110,
    ExpansionHeader1 = 100,
    ExpansionHeader2 = 101,
    ExpansionHeader3 = 102,
    ExpansionHeader4 = 103,

    // --- 110 to 145: Advanced Bill / Cryptographic / Database ---
    BeginBillTableUpgrade = 145,
    FinishBillTableUpgrade = 142,
    RequestCurrencyRevision = 138,
    UploadWindowData = 137,
    StoreEncryptionKey = 136,
    SwitchBaudRate = 129,
    ReadBarCodeData = 124,

    // --- 146 to 169: Bill Validation & Recycler Specifics ---
    RouteBill = 154,
    RequestBillId = 157,
    ModifyBillId = 158,
    RequestBillAcceptorSystemStatus = 159,
    RequestCipherKey = 160,
    ClearCommsStatusBlock = 161,
    RequestClearCommsStatusBlock = 162,
    TestHopper = 163,
    ModifyHopperSecurityCode = 164,
    RequestHopperOptoStatus = 165,
    RequestHopperStatus = 166,
    DispenseHopperCoins = 167,
    RequestAddressMode = 169,

    // --- 170 to 209: Base Hopper, Memory & Counters ---
    RequestBaseHopperStatus = 170,
    EmergencyStop = 171,
    RequestHopperCoinCoinidMap = 172,
    RequestCommsStatusVariables = 173,
    RequestModemStatus = 175,
    ReadDataBlock = 176,
    WriteDataBlock = 177,
    RequestDataBlock = 178,
    CalculateRomChecksum = 180,
    RequestReadyStatus = 181,
    DownloadCalibrationData = 182,
    RequestAsicStatus = 183,
    ReadBufferedBillEvents = 184,
    ModifyRoutingStatus = 185,
    RequestRoutingStatus = 186,
    ModifyRejectionThresholds = 187,
    RequestRejectionThresholds = 188,
    RequestBuildCode = 192,
    RequestFraudCounter = 193,
    RequestRejectCounter = 194,
    RequestAcceptCounter = 195,
    RequestInsertionCounter = 196,
    RequestUserDefinedCounter = 197,
    CountersToEeoprom = 198,
    ConfigurationToEeprom = 199,

    // --- 200 to 224: Advanced Diagnostics & Device Controls ---
    UploadCalibrationData = 200,
    RequestTeachStatus = 201,
    PerformTeachSequence = 202,
    DisplayControl = 203,
    ConfigureLampLines = 204,
    RequestLampLines = 205,
    InhibitInputs = 206,
    ReadInputs = 207,
    WriteOutputs = 209,
    ModifyHopperControlSource = 210,
    RequestHopperControlSource = 211,
    RequestCoinPosition = 212,
    RequestOptionFlags = 213,
    ModifyOptionFlags = 214,
    RequestCoinMechanismCapability = 215,
    RequestDataStorageAvailability = 216,
    RequestServiceStatus = 217,
    ModifyPinNumber = 219,
    RequestSorStatus = 221,
    ModifySorStatus = 222,

    // --- 225 to 255: Core Protocol & Identification ---
    RequestCoinAcceptorSystemStatus = 225,
    RequestIndividualAcceptCounters = 226,
    RequestMasterInhibitStatus = 227,
    ModifyMasterInhibitStatus = 228,
    ReadBufferedCreditOrError = 229,
    RequestInhibitStatus = 230,
    ModifyInhibitStatus = 231,
    PerformSelfTest = 232,
    LatchOutputLines = 233,
    SendDhKey = 234,
    ReadEncryptedEvents = 235,
    ReadMicrocontrollerMustRegs = 236,
    ReadLowestTestedVoltage = 237,
    ReturnCoinId = 240,
    RequestSoftwareRevision = 241,
    RequestSerialNumber = 242,
    RequestDatabaseVersion = 243,
    RequestProductCode = 244,
    RequestEquipmentCategory = 245,
    RequestManufacturerId = 246,
    RequestVariableSet = 247,
    RequestStatus = 248,
    RequestCommsRevision = 249,
    AddressChange = 251,
    AddressClash = 252,
    AddressPoll = 253,
    SimplePoll = 254,
    FactoryReserved = 255,
}

impl core::fmt::Display for CcTalkHeader {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let msg = match self {
            CcTalkHeader::Ack => "Ack",
            CcTalkHeader::ResetDevice => "ResetDevice",
            CcTalkHeader::Broadcast => "Braodcast",
            CcTalkHeader::Nak => "Nak",
            CcTalkHeader::Busy => "Busy",
            CcTalkHeader::RequestEscrowStatus => "Request Escrow Status",
            CcTalkHeader::OperateEscrow => "Operate Escrow",
            CcTalkHeader::SwitchEncryptionKey => "Switch Encryption Key",
            CcTalkHeader::ExpansionHeader1 => "Expansion Header 1",
            CcTalkHeader::ExpansionHeader2 => "Exapansion Header 2",
            CcTalkHeader::ExpansionHeader3 => "Expansion Header 3",
            CcTalkHeader::ExpansionHeader4 => "Expansion Header 4",
            CcTalkHeader::BeginBillTableUpgrade => "Begin Bill Table Upgrade",
            CcTalkHeader::FinishBillTableUpgrade => "Finish Note Table Upgrade",
            CcTalkHeader::RequestCurrencyRevision => "Request Currency Revision",
            CcTalkHeader::UploadWindowData => "Upload Window Data",
            CcTalkHeader::StoreEncryptionKey => "Store Encryption Key",
            CcTalkHeader::SwitchBaudRate => "Switch Baud Rate",
            CcTalkHeader::ReadBarCodeData => "Read Bar Code Data",
            CcTalkHeader::RouteBill => "Route Bill",
            CcTalkHeader::RequestBillId => "Request Bill Id",
            CcTalkHeader::ModifyBillId => "Modify Bill Id",
            CcTalkHeader::RequestBillAcceptorSystemStatus => "Request Bill Acceptor System Status",
            CcTalkHeader::RequestCipherKey => "Request Cipher Key",
            CcTalkHeader::ClearCommsStatusBlock => "Clear Comms Status Block",
            CcTalkHeader::RequestClearCommsStatusBlock => "Request Clear Comms Status Block",
            CcTalkHeader::TestHopper => "Test Hopper",
            CcTalkHeader::ModifyHopperSecurityCode => "Modify Hopper Security Code",
            CcTalkHeader::RequestHopperOptoStatus => "Request Hopper Opto Status",
            CcTalkHeader::RequestHopperStatus => "Request Hopper Status",
            CcTalkHeader::DispenseHopperCoins => "Dispense Hopper Coins",
            CcTalkHeader::RequestAddressMode => "Request Address Mode",
            CcTalkHeader::RequestBaseHopperStatus => "Request Base Hopper Status",
            CcTalkHeader::EmergencyStop => "Emergency Stop",
            CcTalkHeader::RequestHopperCoinCoinidMap => "Request Hopper Coin Id Map",
            CcTalkHeader::RequestCommsStatusVariables => "Request Comms Status Variables",
            CcTalkHeader::RequestModemStatus => "Request Modem Status",
            CcTalkHeader::ReadDataBlock => "Read Data Block",
            CcTalkHeader::WriteDataBlock => "Write Data Block",
            CcTalkHeader::RequestDataBlock => "Request Data Block",
            CcTalkHeader::CalculateRomChecksum => "Calculate Rom Checksum",
            CcTalkHeader::RequestReadyStatus => "Request Ready Status",
            CcTalkHeader::DownloadCalibrationData => "Download Calibration Data",
            CcTalkHeader::RequestAsicStatus => "Request Asic Status",
            CcTalkHeader::ReadBufferedBillEvents => "Read Buffered Bill Events",
            CcTalkHeader::ModifyRoutingStatus => "Modify Routing Status",
            CcTalkHeader::RequestRoutingStatus => "Request Routing Status",
            CcTalkHeader::ModifyRejectionThresholds => "Modify Rejection Thresholds",
            CcTalkHeader::RequestRejectionThresholds => "Request Rejection Thresholds",
            CcTalkHeader::RequestBuildCode => "Request Build Code",
            CcTalkHeader::RequestFraudCounter => "Request Fraud Counter",
            CcTalkHeader::RequestRejectCounter => "Request Reject Counter",
            CcTalkHeader::RequestAcceptCounter => "Request Accept Counter",
            CcTalkHeader::RequestInsertionCounter => "Request Insertion Counter",
            CcTalkHeader::RequestUserDefinedCounter => "Request User Defined Counter",
            CcTalkHeader::CountersToEeoprom => "Counters to EEPROM",
            CcTalkHeader::ConfigurationToEeprom => "Configuration to EEPROM",
            CcTalkHeader::UploadCalibrationData => "Upload Calibration Data",
            CcTalkHeader::RequestTeachStatus => "Request Teach Status",
            CcTalkHeader::PerformTeachSequence => "Perform Teach Sequence",
            CcTalkHeader::DisplayControl => "Display Control",
            CcTalkHeader::ConfigureLampLines => "Configure Lamp Lines",
            CcTalkHeader::RequestLampLines => "Request Lamp Lines",
            CcTalkHeader::InhibitInputs => "Inhibit Inputs",
            CcTalkHeader::ReadInputs => "Read Inputs",
            CcTalkHeader::WriteOutputs => "Write Outputs",
            CcTalkHeader::ModifyHopperControlSource => "Modify Hopper Control Source",
            CcTalkHeader::RequestHopperControlSource => "Request Hopper Control Source",
            CcTalkHeader::RequestCoinPosition => "Request Coin Position",
            CcTalkHeader::RequestOptionFlags => "Request Option Flags",
            CcTalkHeader::ModifyOptionFlags => "Modify Option Flags",
            CcTalkHeader::RequestCoinMechanismCapability => "Request Coin Machanism Capability",
            CcTalkHeader::RequestDataStorageAvailability => "Request Data Storage Availability",
            CcTalkHeader::RequestServiceStatus => "Request Service Status",
            CcTalkHeader::ModifyPinNumber => "Modify Pin Number",
            CcTalkHeader::RequestSorStatus => "Request Sor Status",
            CcTalkHeader::ModifySorStatus => "Modify Sor Status",
            CcTalkHeader::RequestCoinAcceptorSystemStatus => "Request Coin Acceptor System Status",
            CcTalkHeader::RequestIndividualAcceptCounters => "Request Individual Acceptor Counters",
            CcTalkHeader::RequestMasterInhibitStatus => "Request Master Inhibit Status",
            CcTalkHeader::ModifyMasterInhibitStatus => "Modify Master Inhibit Service",
            CcTalkHeader::ReadBufferedCreditOrError => "Read Buffered Credit or Error",
            CcTalkHeader::RequestInhibitStatus => "Request Inhibit Status",
            CcTalkHeader::ModifyInhibitStatus => "Modify Inhibit Status",
            CcTalkHeader::PerformSelfTest => "Perform Self Test",
            CcTalkHeader::LatchOutputLines => "Latch Output Lines",
            CcTalkHeader::SendDhKey => "Send Diffy-Helman Key",
            CcTalkHeader::ReadEncryptedEvents => "Read Encrypted Events",
            CcTalkHeader::ReadMicrocontrollerMustRegs => "Read uController Must Regs",
            CcTalkHeader::ReadLowestTestedVoltage => "read Lowest Tested Voltage",
            CcTalkHeader::ReturnCoinId => "Return Coin Id",
            CcTalkHeader::RequestSoftwareRevision => "Request Software Revision",
            CcTalkHeader::RequestSerialNumber => "request Serial Number",
            CcTalkHeader::RequestDatabaseVersion => "Request Database Version",
            CcTalkHeader::RequestProductCode => "Request Product Code",
            CcTalkHeader::RequestEquipmentCategory => "Request Equipment Category",
            CcTalkHeader::RequestManufacturerId => "Request Manufacturer Id",
            CcTalkHeader::RequestVariableSet => "Request Variable Set",
            CcTalkHeader::RequestStatus => "Request Status",
            CcTalkHeader::RequestCommsRevision => "Request Comms Revision",
            CcTalkHeader::AddressChange => "Address Change",
            CcTalkHeader::AddressClash => "Address Clash",
            CcTalkHeader::AddressPoll => "Address Poll",
            CcTalkHeader::SimplePoll => "Simple Poll",
            CcTalkHeader::FactoryReserved => "Factory Reserved",
            CcTalkHeader::UknownHeader => "Error: Unknown Header",
        };

        write!(f, "{}", msg)
    }
}
impl From<u8> for CcTalkHeader {
    fn from(value: u8) -> Self {
        match value {
            // --- 0 to 9: Response & Broadcast Codes --
            0 => CcTalkHeader::Ack,
            1 => CcTalkHeader::ResetDevice,
            2 => CcTalkHeader::Broadcast,
            5 => CcTalkHeader::Nak,
            6 => CcTalkHeader::Busy,

            // --- 100 to 109: Escrow & Expansion ---
            100 => CcTalkHeader::ExpansionHeader1,
            101 => CcTalkHeader::ExpansionHeader2,
            102 => CcTalkHeader::ExpansionHeader3,
            103 => CcTalkHeader::ExpansionHeader4,
            106 => CcTalkHeader::RequestEscrowStatus,
            107 => CcTalkHeader::OperateEscrow,
            110 => CcTalkHeader::SwitchEncryptionKey,

            // --- 110 to 145: Advanced Bill / Cryptographic / Database --
            124 => CcTalkHeader::ReadBarCodeData,
            129 => CcTalkHeader::SwitchBaudRate,
            136 => CcTalkHeader::StoreEncryptionKey,
            137 => CcTalkHeader::UploadWindowData,
            138 => CcTalkHeader::RequestCurrencyRevision,
            142 => CcTalkHeader::FinishBillTableUpgrade,
            145 => CcTalkHeader::BeginBillTableUpgrade,

            // --- 146 to 169: Bill Validation & Recycler Specifics ---
            154 => CcTalkHeader::RouteBill,
            157 => CcTalkHeader::RequestBillId,
            158 => CcTalkHeader::ModifyBillId,
            159 => CcTalkHeader::RequestBillAcceptorSystemStatus,
            160 => CcTalkHeader::RequestCipherKey,
            161 => CcTalkHeader::ClearCommsStatusBlock,
            162 => CcTalkHeader::RequestClearCommsStatusBlock,
            163 => CcTalkHeader::TestHopper,
            164 => CcTalkHeader::ModifyHopperSecurityCode,
            165 => CcTalkHeader::RequestHopperOptoStatus,
            166 => CcTalkHeader::RequestHopperStatus,
            167 => CcTalkHeader::DispenseHopperCoins,
            169 => CcTalkHeader::RequestAddressMode,

            // --- 170 to 209: Base Hopper, Memory & Counters ---
            170 => CcTalkHeader::RequestBaseHopperStatus,
            171 => CcTalkHeader::EmergencyStop,
            172 => CcTalkHeader::RequestHopperCoinCoinidMap,
            173 => CcTalkHeader::RequestCommsStatusVariables,
            175 => CcTalkHeader::RequestModemStatus,
            176 => CcTalkHeader::ReadDataBlock,
            177 => CcTalkHeader::WriteDataBlock,
            178 => CcTalkHeader::RequestDataBlock,
            180 => CcTalkHeader::CalculateRomChecksum,
            181 => CcTalkHeader::RequestReadyStatus,
            182 => CcTalkHeader::DownloadCalibrationData,
            183 => CcTalkHeader::RequestAsicStatus,
            184 => CcTalkHeader::ReadBufferedBillEvents,
            185 => CcTalkHeader::ModifyRoutingStatus,
            186 => CcTalkHeader::RequestRoutingStatus,
            187 => CcTalkHeader::ModifyRejectionThresholds,
            188 => CcTalkHeader::RequestRejectionThresholds,
            192 => CcTalkHeader::RequestBuildCode,
            193 => CcTalkHeader::RequestFraudCounter,
            194 => CcTalkHeader::RequestRejectCounter,
            195 => CcTalkHeader::RequestAcceptCounter,
            196 => CcTalkHeader::RequestInsertionCounter,
            197 => CcTalkHeader::RequestUserDefinedCounter,
            198 => CcTalkHeader::CountersToEeoprom,
            199 => CcTalkHeader::ConfigurationToEeprom,
            200 => CcTalkHeader::UploadCalibrationData,
            201 => CcTalkHeader::RequestTeachStatus,
            202 => CcTalkHeader::PerformTeachSequence,
            203 => CcTalkHeader::DisplayControl,
            204 => CcTalkHeader::ConfigureLampLines,
            205 => CcTalkHeader::RequestLampLines,
            206 => CcTalkHeader::InhibitInputs,
            207 => CcTalkHeader::ReadInputs,
            209 => CcTalkHeader::WriteOutputs,

            // --- 200 to 224: Advanced Diagnostics & Device Controls ---
            210 => CcTalkHeader::ModifyHopperControlSource,
            211 => CcTalkHeader::RequestHopperControlSource,
            212 => CcTalkHeader::RequestCoinPosition,
            213 => CcTalkHeader::RequestOptionFlags,
            214 => CcTalkHeader::ModifyOptionFlags,
            215 => CcTalkHeader::RequestCoinMechanismCapability,
            216 => CcTalkHeader::RequestDataStorageAvailability,
            217 => CcTalkHeader::RequestServiceStatus,
            219 => CcTalkHeader::ModifyPinNumber,
            221 => CcTalkHeader::RequestSorStatus,
            222 => CcTalkHeader::ModifySorStatus,

            // --- 225 to 255: Core Protocol & Identification --
            225 => CcTalkHeader::RequestCoinAcceptorSystemStatus,
            226 => CcTalkHeader::RequestIndividualAcceptCounters,
            227 => CcTalkHeader::RequestMasterInhibitStatus,
            228 => CcTalkHeader::ModifyMasterInhibitStatus,
            229 => CcTalkHeader::ReadBufferedCreditOrError,
            230 => CcTalkHeader::RequestInhibitStatus,
            231 => CcTalkHeader::ModifyInhibitStatus,
            232 => CcTalkHeader::PerformSelfTest,
            233 => CcTalkHeader::LatchOutputLines,
            234 => CcTalkHeader::SendDhKey,
            235 => CcTalkHeader::ReadEncryptedEvents,
            236 => CcTalkHeader::ReadMicrocontrollerMustRegs,
            237 => CcTalkHeader::ReadLowestTestedVoltage,
            240 => CcTalkHeader::ReturnCoinId,
            241 => CcTalkHeader::RequestSoftwareRevision,
            242 => CcTalkHeader::RequestSerialNumber,
            243 => CcTalkHeader::RequestDatabaseVersion,
            244 => CcTalkHeader::RequestProductCode,
            245 => CcTalkHeader::RequestEquipmentCategory,
            246 => CcTalkHeader::RequestManufacturerId,
            247 => CcTalkHeader::RequestVariableSet,
            248 => CcTalkHeader::RequestStatus,
            249 => CcTalkHeader::RequestCommsRevision,
            251 => CcTalkHeader::AddressChange,
            252 => CcTalkHeader::AddressClash,
            253 => CcTalkHeader::AddressPoll,
            254 => CcTalkHeader::SimplePoll,
            255 => CcTalkHeader::FactoryReserved,
            _ => CcTalkHeader::UknownHeader,
        }
    }
}
