use std::convert::TryFrom;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum CcTalkHeader {
    // --- 0 to 9: Response & Broadcast Codes ---
    Ack = 0,
    ResetDevice = 1,
    Broadcast = 2,
    Nak = 5,
    Busy = 6,

    // --- 100 to 109: Escrow & Expansion ---
    RequestEscrowStatus = 106,
    OperateEscrow = 107,
    SwitchEncryptionKey = 110,
    ExpansionHeader1 = 100,
    ExpansionHeader2 = 101,
    ExpansionHeader3 = 102,
    ExpansionHeader4 = 103,

    // --- 110 to 145: Advanced Bill / Cryptographic / Database ---
    BeginBillTableUpgrade = 145,
    FinishBillTableUpgrade = 142,
    RequestCurrencyRevision = 138,
    UploadWindowData = 137,
    StoreEncryptionKey = 136,
    SwitchBaudRate = 129,
    ReadBarCodeData = 124,

    // --- 146 to 169: Bill Validation & Recycler Specifics ---
    RouteBill = 154,
    RequestBillId = 157,
    ModifyBillId = 158,
    RequestBillAcceptorSystemStatus = 159,
    RequestCipherKey = 160,
    ClearCommsStatusBlock = 161,
    RequestClearCommsStatusBlock = 162,
    TestHopper = 163,
    ModifyHopperSecurityCode = 164,
    RequestHopperOptoStatus = 165,
    RequestHopperStatus = 166,
    DispenseHopperCoins = 167,
    RequestAddressMode = 169,

    // --- 170 to 209: Base Hopper, Memory & Counters ---
    RequestBaseHopperStatus = 170,
    EmergencyStop = 171,
    RequestHopperCoinCoinidMap = 172,
    RequestCommsStatusVariables = 173,
    RequestModemStatus = 175,
    ReadDataBlock = 176,
    WriteDataBlock = 177,
    RequestDataBlock = 178,
    CalculateRomChecksum = 180,
    RequestReadyStatus = 181,
    DownloadCalibrationData = 182,
    RequestAsicStatus = 183,
    ReadBufferedBillEvents = 184,
    ModifyRoutingStatus = 185,
    RequestRoutingStatus = 186,
    ModifyRejectionThresholds = 187,
    RequestRejectionThresholds = 188,
    RequestBuildCode = 192,
    RequestFraudCounter = 193,
    RequestRejectCounter = 194,
    RequestAcceptCounter = 195,
    RequestInsertionCounter = 196,
    RequestUserDefinedCounter = 197,
    CountersToEeoprom = 198,
    ConfigurationToEeprom = 199,

    // --- 200 to 224: Advanced Diagnostics & Device Controls ---
    UploadCalibrationData = 200,
    RequestTeachStatus = 201,
    PerformTeachSequence = 202,
    DisplayControl = 203,
    ConfigureLampLines = 204,
    RequestLampLines = 205,
    InhibitInputs = 206,
    ReadInputs = 207,
    WriteOutputs = 209,
    ModifyHopperControlSource = 210,
    RequestHopperControlSource = 211,
    RequestCoinPosition = 212,
    RequestOptionFlags = 213,
    ModifyOptionFlags = 214,
    RequestCoinMechanismCapability = 215,
    RequestDataStorageAvailability = 216,
    RequestServiceStatus = 217,
    ModifyPinNumber = 219,
    RequestSorStatus = 221,
    ModifySorStatus = 222,

    // --- 225 to 255: Core Protocol & Identification ---
    RequestCoinAcceptorSystemStatus = 225,
    RequestIndividualAcceptCounters = 226,
    RequestMasterInhibitStatus = 227,
    ModifyMasterInhibitStatus = 228,
    ReadBufferedCreditOrError = 229,
    RequestInhibitStatus = 230,
    ModifyInhibitStatus = 231,
    PerformSelfTest = 232,
    LatchOutputLines = 233,
    SendDhKey = 234,
    ReadEncryptedEvents = 235,
    ReadMicrocontrollerMustRegs = 236,
    ReadLowestTestedVoltage = 237,
    ReturnCoinId = 240,
    RequestSoftwareRevision = 241,
    RequestSerialNumber = 242,
    RequestDatabaseVersion = 243,
    RequestProductCode = 244,
    RequestEquipmentCategory = 245,
    RequestManufacturerId = 246,
    RequestVariableSet = 247,
    RequestStatus = 248,
    RequestCommsRevision = 249,
    AddressChange = 251,
    AddressClash = 252,
    AddressPoll = 253,
    SimplePoll = 254,
    FactoryReserved = 255,
}

impl TryFrom<u8> for CcTalkHeader {
    type Error = u8;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            // --- 0 to 9: Response & Broadcast Codes --
            0 => Ok(CcTalkHeader::Ack),
            1 => Ok(CcTalkHeader::ResetDevice),
            2 => Ok(CcTalkHeader::Broadcast),
            5 => Ok(CcTalkHeader::Nak),
            6 => Ok(CcTalkHeader::Busy),

            // --- 100 to 109: Escrow & Expansion ---
            100 => Ok(CcTalkHeader::ExpansionHeader1),
            101 => Ok(CcTalkHeader::ExpansionHeader2),
            102 => Ok(CcTalkHeader::ExpansionHeader3),
            103 => Ok(CcTalkHeader::ExpansionHeader4),
            106 => Ok(CcTalkHeader::RequestEscrowStatus),
            107 => Ok(CcTalkHeader::OperateEscrow),
            110 => Ok(CcTalkHeader::SwitchEncryptionKey),

            // --- 110 to 145: Advanced Bill / Cryptographic / Database --
            124 => Ok(CcTalkHeader::ReadBarCodeData),
            129 => Ok(CcTalkHeader::SwitchBaudRate),
            136 => Ok(CcTalkHeader::StoreEncryptionKey),
            137 => Ok(CcTalkHeader::UploadWindowData),
            138 => Ok(CcTalkHeader::RequestCurrencyRevision),
            142 => Ok(CcTalkHeader::FinishBillTableUpgrade),
            145 => Ok(CcTalkHeader::BeginBillTableUpgrade),

            // --- 146 to 169: Bill Validation & Recycler Specifics ---
            154 => Ok(CcTalkHeader::RouteBill),
            157 => Ok(CcTalkHeader::RequestBillId),
            158 => Ok(CcTalkHeader::ModifyBillId),
            159 => Ok(CcTalkHeader::RequestBillAcceptorSystemStatus),
            160 => Ok(CcTalkHeader::RequestCipherKey),
            161 => Ok(CcTalkHeader::ClearCommsStatusBlock),
            162 => Ok(CcTalkHeader::RequestClearCommsStatusBlock),
            163 => Ok(CcTalkHeader::TestHopper),
            164 => Ok(CcTalkHeader::ModifyHopperSecurityCode),
            165 => Ok(CcTalkHeader::RequestHopperOptoStatus),
            166 => Ok(CcTalkHeader::RequestHopperStatus),
            167 => Ok(CcTalkHeader::DispenseHopperCoins),
            169 => Ok(CcTalkHeader::RequestAddressMode),

            // --- 170 to 209: Base Hopper, Memory & Counters ---
            170 => Ok(CcTalkHeader::RequestBaseHopperStatus),
            171 => Ok(CcTalkHeader::EmergencyStop),
            172 => Ok(CcTalkHeader::RequestHopperCoinCoinidMap),
            173 => Ok(CcTalkHeader::RequestCommsStatusVariables),
            175 => Ok(CcTalkHeader::RequestModemStatus),
            176 => Ok(CcTalkHeader::ReadDataBlock),
            177 => Ok(CcTalkHeader::WriteDataBlock),
            178 => Ok(CcTalkHeader::RequestDataBlock),
            180 => Ok(CcTalkHeader::CalculateRomChecksum),
            181 => Ok(CcTalkHeader::RequestReadyStatus),
            182 => Ok(CcTalkHeader::DownloadCalibrationData),
            183 => Ok(CcTalkHeader::RequestAsicStatus),
            184 => Ok(CcTalkHeader::ReadBufferedBillEvents),
            185 => Ok(CcTalkHeader::ModifyRoutingStatus),
            186 => Ok(CcTalkHeader::RequestRoutingStatus),
            187 => Ok(CcTalkHeader::ModifyRejectionThresholds),
            188 => Ok(CcTalkHeader::RequestRejectionThresholds),
            192 => Ok(CcTalkHeader::RequestBuildCode),
            193 => Ok(CcTalkHeader::RequestFraudCounter),
            194 => Ok(CcTalkHeader::RequestRejectCounter),
            195 => Ok(CcTalkHeader::RequestAcceptCounter),
            196 => Ok(CcTalkHeader::RequestInsertionCounter),
            197 => Ok(CcTalkHeader::RequestUserDefinedCounter),
            198 => Ok(CcTalkHeader::CountersToEeoprom),
            199 => Ok(CcTalkHeader::ConfigurationToEeprom),
            200 => Ok(CcTalkHeader::UploadCalibrationData),
            201 => Ok(CcTalkHeader::RequestTeachStatus),
            202 => Ok(CcTalkHeader::PerformTeachSequence),
            203 => Ok(CcTalkHeader::DisplayControl),
            204 => Ok(CcTalkHeader::ConfigureLampLines),
            205 => Ok(CcTalkHeader::RequestLampLines),
            206 => Ok(CcTalkHeader::InhibitInputs),
            207 => Ok(CcTalkHeader::ReadInputs),
            209 => Ok(CcTalkHeader::WriteOutputs),

            // --- 200 to 224: Advanced Diagnostics & Device Controls ---
            210 => Ok(CcTalkHeader::ModifyHopperControlSource),
            211 => Ok(CcTalkHeader::RequestHopperControlSource),
            212 => Ok(CcTalkHeader::RequestCoinPosition),
            213 => Ok(CcTalkHeader::RequestOptionFlags),
            214 => Ok(CcTalkHeader::ModifyOptionFlags),
            215 => Ok(CcTalkHeader::RequestCoinMechanismCapability),
            216 => Ok(CcTalkHeader::RequestDataStorageAvailability),
            217 => Ok(CcTalkHeader::RequestServiceStatus),
            219 => Ok(CcTalkHeader::ModifyPinNumber),
            221 => Ok(CcTalkHeader::RequestSorStatus),
            222 => Ok(CcTalkHeader::ModifySorStatus),

            // --- 225 to 255: Core Protocol & Identification ---
            225 => Ok(CcTalkHeader::RequestCoinAcceptorSystemStatus),
            226 => Ok(CcTalkHeader::RequestIndividualAcceptCounters),
            227 => Ok(CcTalkHeader::RequestMasterInhibitStatus),
            228 => Ok(CcTalkHeader::ModifyMasterInhibitStatus),
            229 => Ok(CcTalkHeader::ReadBufferedCreditOrError),
            230 => Ok(CcTalkHeader::RequestInhibitStatus),
            231 => Ok(CcTalkHeader::ModifyInhibitStatus),
            232 => Ok(CcTalkHeader::PerformSelfTest),
            233 => Ok(CcTalkHeader::LatchOutputLines),
            234 => Ok(CcTalkHeader::SendDhKey),
            235 => Ok(CcTalkHeader::ReadEncryptedEvents),
            236 => Ok(CcTalkHeader::ReadMicrocontrollerMustRegs),
            237 => Ok(CcTalkHeader::ReadLowestTestedVoltage),
            240 => Ok(CcTalkHeader::ReturnCoinId),
            241 => Ok(CcTalkHeader::RequestSoftwareRevision),
            242 => Ok(CcTalkHeader::RequestSerialNumber),
            243 => Ok(CcTalkHeader::RequestDatabaseVersion),
            244 => Ok(CcTalkHeader::RequestProductCode),
            245 => Ok(CcTalkHeader::RequestEquipmentCategory),
            246 => Ok(CcTalkHeader::RequestManufacturerId),
            247 => Ok(CcTalkHeader::RequestVariableSet),
            248 => Ok(CcTalkHeader::RequestStatus),
            249 => Ok(CcTalkHeader::RequestCommsRevision),
            251 => Ok(CcTalkHeader::AddressChange),
            252 => Ok(CcTalkHeader::AddressClash),
            253 => Ok(CcTalkHeader::AddressPoll),
            254 => Ok(CcTalkHeader::SimplePoll),
            255 => Ok(CcTalkHeader::FactoryReserved),
            _ => Err(value),
        }
    }
}
